config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :tickets

  get 'tickets/bon_reparation', :to => 'tickets#bon_reparation'



  root to: 'accueil#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/administrateur.rb
class Administrateur < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ticket.rb
class Ticket < ApplicationRecord

    validates :mail, presence: true 
end

app/controllers/accueil_controller.rb
class AccueilController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[ show edit update destroy ]

  # GET /tickets or /tickets.json
  def index
    @tickets = Ticket.all
  end


  # def bon_reparation
   
  #   respond_to do |format|
  #     format.html
  #     format.pdf do
       
  #       render :pdf => "TicketReparation", template: "tickets/bon_reparation.html.erb",formats: :HTML, 
  #       encoding: 'utf8'
  #     end
  #   end
  # end

  
  # GET /tickets/1 or /tickets/1.json Etiquette sur téléphone

  def show
    respond_to do |format|
      format.html
      format.pdf do
       
        render :pdf => "TicketReparation",
         template: "tickets/ticket.html.erb",
        layout: "pdf",
        page_size: 'A4',
        formats: :HTML, 
        encoding: 'utf8'
      end

  

   
    end
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets or /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: "Ticket crée avec succès." }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1 or /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: "Ticket crée avec succès" }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1 or /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: "Ticket Supprimé." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:createur, :raisonSocial, :nom, :prenom, :numero, :mail, :modele, :imei, :motdepass, :panne, :delai, :remarque, :total, :accompte, :reduction, :garantie, :statut, :paye)
    end
end

app/helpers/accueil_helper.rb
module AccueilHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/accueil/index.html.erb
<div class="container-fluid">
  <% if admin_signed_in? %>

    <div class="row"> 

    <div class="column d-flex justify-content-center mt-4"> 

  
  
      <%= link_to "Se déconnecter", destroy_admin_session_path, class:"btn btn-danger m-2", style: "background-color: #ff0066;" , method: :delete %>

 
     
  
      <%= link_to "Créer un ticket", new_ticket_path, class:"btn btn-danger m-2 text-white ", style: "background-color: #ff0066;"  %>

        <%= link_to "Voir les tickets", 'tickets', class:"btn btn-danger m-2 text-white ", style: "background-color: #ff0066;"  %>


    
        
   
   

      

      <%= link_to "Changer son e-mail / mot de passe", edit_admin_registration_path,class:"btn btn-danger m-2",  style: "background-color: #ff0066;" %>
       
  
    </div>
      </div>
  </div>

  
 

  <% else %>

  <div class="container-fluid">
  <div class="row">
  <div class="column d-flex justify-content-center mt-4 ">

  
     
      <%= link_to "Se connecter", new_admin_session_path,class:"btn btn-danger m-2 text-white",  style: "background-color: #ff0066;" %>
    

    
      <%# <%= link_to "S'enregistrer", new_admin_registration_path, class:"btn btn-danger m-2",  style: "background-color: #ff0066;" %>

  </div>
    </div>
      </div>


  <% end %>


 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MobileCenter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
  </head>

  <body class="text-white text-center" style="background-color:#04191b;">
  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

       <div class="container-fluid ">
          <div class="row">
              <div class="column text-center">

        <%= link_to root_path do %>
   <%= image_tag "https://static.wixstatic.com/media/12d462_c75886e9f8524a6ead37a4cf72987ffb~mv2.png/v1/fill/w_119,h_35,al_c,q_95/Logo%20vectowhite.webp" %>
<% end %>
           
            
              </div> 
              </div>
        </div>
    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
    <%= wicked_pdf_stylesheet_link_tag "pdf" -%>
  
  </head>
  <body onload='number_pages'>
    <div id="header">
    

    </div>
    <div id="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tickets/_form.html.erb
<% if admin_signed_in?  %>
<%= form_with(model: ticket, local: true, class:"text-white formulaire d-flex justify-content-center align-items-center ") do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="d-flex flex-column m-4">

  <style>
    h2 {
      font-size: 14px;
    }

    .valider {
      font-size: 14px;
    }

    .field {
      font-size:12px;
    }

    .text {
      border-radius: 10px;
      color:#88c4c9;
    }

    .field {
      padding: 15px;
      
    }

    .formulaire {
      margin-left: 10%;
    }

    
  </style>

  

    <h2> Client </h2>

    

    <div class="field d-flex flex-column">
    <%= form.label :createur, value: "Crée par" %>
    <%= form.text_field :createur, style: "background-color: #1d4043;", class: "text" %>
  </div>

  <div class="field d-flex flex-column">
    <%= form.label :raisonSocial, value: "Raison sociale" %>
    <%= form.text_field :raisonSocial, style: "background-color: #1d4043;", class: "text" %>
  </div>

  <div class="field field d-flex flex-column">
    <%= form.label :nom %>
    <%= form.text_field :nom, style: "background-color: #1d4043;",class: "text", required: true%>
  </div>

  <div class="field field d-flex flex-column">
    <%= form.label :prenom %>
    <%= form.text_field :prenom,  style: "background-color: #1d4043;",class: "text", required: true  %>
  </div>

  <div class="field field d-flex flex-column">
    <%= form.label :numero %>
    <%= form.number_field :numero,  style: "background-color: #1d4043;",class: "text"  %>
  </div>

  <div class="field field d-flex flex-column">
    <%= form.label :mail %>
    <%= form.text_field :mail,  style: "background-color: #1d4043;",class: "text", required: true  %>
  </div>

  </div>

  <div class="d-flex flex-column m-4">

    <h2> Mobile </h2>

  <div class="field field d-flex flex-column">
    <%= form.label :modele, "Modèle du mobile" %>
    <%= form.text_field :modele,  style: "background-color: #1d4043;",class: "text", required: true   %>
  </div>

  <div class="field field d-flex flex-column">
    <%= form.label :imei, "IMEI" %>
    <%= form.number_field :imei,  style: "background-color: #1d4043;",class: "text"  %>
  </div>

  <div class="field field d-flex flex-column">
    <%= form.label :motdepass, "Mot de passe du téléphone" %>
    <%= form.text_field :motdepass,  style: "background-color: #1d4043;",class: "text"  %>
  </div>

  <div class="field field d-flex flex-column">
    <%= form.label :panne, "Type de Panne" %>
    <%= form.select :panne, ['Ecran','Vitre arrière ','Batterie', 'HP interne', 'HP externe', 'micro', 'bouton on/off', 'Volume', 'Autre ..'],  style: "background-color: #1d4043;",class: "text"  %>
  </div>

  <div class="field field d-flex flex-column">
    <%= form.label :remarque, "Remarque" %>
    <%= form.text_area :remarque,  style: "background-color: #1d4043;",class: "text"  %>
  </div>

  </div>

  <div class="d-flex flex-column m-4 ">

  <h2 class="pt-4"> Facturation </h2>

  <div class="field field d-flex flex-column">
    <%= form.label :total, "Total" %>
    <%= form.text_field :total,  style: "background-color: #1d4043;",class: "text", required: true   %>
  </div>

  <div class="field field d-flex flex-column">
    <%= form.label :accompte, "Accompte" %>
    <%= form.text_field :accompte,  style: "background-color: #1d4043;",class: "text"  %>
  </div>

  <div class="field field d-flex flex-column">
    <%= form.label :reduction, "Réduction" %>
    <%= form.text_field :reduction,  style: "background-color: #1d4043;",class: "text"  %>
  </div>

   <div class="field field d-flex flex-column">
    <%= form.label :statut, "Status" %>
    <%= form.select :statut, ['Réceptionné', 'En cours de réparation', 'Réparé'],  style: "background-color: #1d4043;",class: "text"  %>
  </div>

  <div class="field field d-flex flex-column">
    <%= form.label :delai, "Délais" %>
    <%= form.select :delai, ['0', '24h', '48h', '72h'],  style: "background-color: #1d4043;",class: "text"  %>
  </div>

    <div class="field field d-flex flex-column">
    <%= form.label :paye, "Paiement" %>
    <%= form.select :paye, ['En attende de paiement', 'Accompte Réglé', 'Total Réglé'],  style: "background-color: #1d4043;",class: "text"  %>
  </div>


  <div class="field field d-flex flex-column">
    <%= form.label :garantie, "Garantie" %>
    <%= form.select :garantie, ['0', '6 mois', '12 mois'],  style: "background-color: #1d4043;",class: "text"  %>
  </div>

  
  </div>

  <div class="actions">
   
    <%= form.submit value:"Créer un ticket", class:"btn btn-danger valider",style: "background-color: #ff0066;" %>
  </div>

  
<% end %>


<% else  %>

<h2>Vous n'avez pas accès à cette page veuillez vous connecter. </h2>

<% end %>

app/views/tickets/bon_reparation.html.erb


<p>
  <strong>Raisonsocial:</strong>
  <%= @ticket.raisonSocial %>
</p>

<p>
  <strong>Nom:</strong>
  <%= @ticket.nom %>
</p>

<p>
  <strong>Prenom:</strong>
  <%= @ticket.prenom %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @ticket.numero %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @ticket.mail %>
</p>

<p>
  <strong>Modele:</strong>
  <%= @ticket.modele %>
</p>

<p>
  <strong>Imei:</strong>
  <%= @ticket.imei %>
</p>

<p>
  <strong>Motdepass:</strong>
  <%= @ticket.motdepass %>
</p>

<p>
  <strong>Panne:</strong>
  <%= @ticket.panne %>
</p>

<p>
  <strong>Remarque:</strong>
  <%= @ticket.remarque %>
</p>

<p>
  <strong>Total:</strong>
  <%= @ticket.total %>
</p>

<p>
  <strong>Accompte:</strong>
  <%= @ticket.accompte %>
</p>

<p>
  <strong>Reduction:</strong>
  <%= @ticket.reduction %>
</p>

<p>
  <strong>Garantie:</strong>
  <%= @ticket.garantie %>
</p>







app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Afficher', @ticket %> |
<%= link_to 'retour', tickets_path %>

app/views/tickets/index.html.erb
<% if admin_signed_in?  %>

<p id="notice"><%= notice %></p>

<style>
tr  {
  border: 1px solid white;
}

th {
  padding:5px;
}

td {
  padding:5px;
}


</style>

<h1>Tickets</h1>

<table>
  <thead>
    <tr>
      <th>Raisonsocial</th>
      <th>Nom</th>
      <th>Prenom</th>
      <th>Numero</th>
      <th>Mail</th>
      <th>Modele</th>
      <th>Imei</th>
      <th>Motdepass</th>
      <th>Panne</th>
      <th>Remarque</th>
      <th>Total</th>
      <th>Accompte</th>
      <th>Reduction</th>
      <th>Garantie</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.raisonSocial %></td>
        <td><%= ticket.nom %></td>
        <td><%= ticket.prenom %></td>
        <td><%= ticket.numero %></td>
        <td><%= ticket.mail %></td>
        <td><%= ticket.modele %></td>
        <td><%= ticket.imei %></td>
        <td><%= ticket.motdepass %></td>
        <td><%= ticket.panne %></td>
        <td><%= ticket.remarque %></td>
        <td><%= ticket.total %></td>
        <td><%= ticket.accompte %></td>
        <td><%= ticket.reduction %></td>
        <td><%= ticket.garantie %></td>

        <td><%= link_to 'Afficher', ticket, class: "btn btn-danger", style: "background-color:#ff0066" %></td>
        <td><%= link_to 'Modifier', edit_ticket_path(ticket), class: "btn btn-danger", style: "background-color:#ff0066" %></td>
        <td><%= link_to 'Supprimer', ticket, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger", style: "background-color:#ff0066" %></td>
      
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Créer un nouveau ticket', new_ticket_path, class: "btn btn-danger", style: "background-color:#ff0066" %>


<% else  %>

<h2>Vous n'avez pas accès à cette page veuillez vous connecter. </h2>

<% end %>

app/views/tickets/new.html.erb
<h3 class="text-white text-center mt-2" ></h3>

<%= render 'form', ticket: @ticket %>

<%link_to 'Retour', tickets_path%>

app/views/tickets/show.html.erb
<% if admin_signed_in? %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Crée par: </strong>
  <%= @ticket.createur %>
</p>

<p>
  <strong>Raison sociale :</strong>
  <%= @ticket.raisonSocial %>
</p>

<p>
  <strong>Nom:</strong>
  <%= @ticket.nom %>
</p>

<p>
  <strong>Prenom:</strong>
  <%= @ticket.prenom %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @ticket.numero %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @ticket.mail %>
</p>

<p>
  <strong>Modele:</strong>
  <%= @ticket.modele %>
</p>

<p>
  <strong>Imei:</strong>
  <%= @ticket.imei %>
</p>

<p>
  <strong>Motdepass:</strong>
  <%= @ticket.motdepass %>
</p>

<p>
  <strong>Panne:</strong>
  <%= @ticket.panne %>
</p>

<p>
  <strong>Délai :</strong>
  <%= @ticket.delai %>
</p>

<p>
  <strong>Remarque :</strong>
  
  <%= @ticket.remarque %>
</p>

<p>
  <strong>Total:</strong>
  <%= @ticket.total %>
</p>

<p>
  <strong>Accompte:</strong>
  <%= @ticket.accompte %>
</p>

<p>
  <strong>Reduction:</strong>
  <%= @ticket.reduction %>
</p>

<p>
  <strong>Garantie:</strong>
  <%= @ticket.garantie %>
</p>

<p>
  <strong>Status:</strong>
  <%= @ticket.statut %>
</p>

<p>
  <strong>Paiement:</strong>
  <%= @ticket.paye %>
</p>

<%= link_to 'Modifier', edit_ticket_path(@ticket), class: "btn btn-danger text-white m-2", style: "background-color: rgba(178,29,94);"  %> 
<%= link_to 'Retour', tickets_path, class: "btn btn-danger text-white m-2", style: "background-color: rgba(178,29,94);"  %>
<%= link_to "PDF", ticket_path(format: :pdf), class: "btn btn-danger text-white m-2", style: "background-color: rgba(178,29,94);"  %>
<% else %>

<h2> Vous n'êtes pas connecté et n'avez pas les droits d'accès à cette page ! veuillez vous connecter. </h2>

<% end %>

app/views/tickets/ticket.html.erb
<style>

/* .parent-logo {
  width:100%;
  display:flex;
  flex-direction:column;
  justify-content:right;
  align-items:right;
} */

/* .global1 {
  width:70mm;
  height:12mm;
}

.global2 {
  width:38mm;
  height:25mm;
} */

h3 {
  text-align:right;
}

.logo {
  height:50px;
  padding-left:80%;

}

.logo2 {
  height:50px;
  padding-left:20%;


}
</style>


<%# <p style='page-break-after:always;'></p> %>

<div class="toto">

  <strong> N'<%= @ticket.id %> </strong>


<br>
  <%= @ticket.created_at.to_formatted_s(:short)  %> <br>

  <strong> <%= @ticket.nom.upcase %> </strong> <br> 

  Panne:
  <%= @ticket.panne %> <br>

  MP :
  <%= @ticket.motdepass %>

</div>

<p style='page-break-after:always;'></p>



<div class="toto2">

  <strong> Ticket numéro :  <%= @ticket.id %>  </strong>


<br> <br>
  Date :  <%= @ticket.created_at.to_formatted_s(:short)  %>



</div>




<div class="middle">



<p>
  <strong>Nom:</strong>
  <%= @ticket.nom %>
</p>

<p>
  <strong>Prenom:</strong>
  <%= @ticket.prenom %>
</p>

<p>
  <strong>Numéro :</strong>
  0<%= @ticket.numero %>
</p>

<p>
  <strong>Mail :</strong>
  <%= @ticket.mail %>
</p>

</div>

<div class="end">

<p>
  <strong>Modèle :</strong>
  <%= @ticket.modele %>
</p>

<p>
  <strong>IMEI :</strong>
  <%= @ticket.imei %>
</p>

<p>
  <strong>Mot de passe :</strong>
  <%= @ticket.motdepass %>
</p>



<p>
  <strong>Panne:</strong>
  <%= @ticket.panne %>
</p>

<p>
  <strong>Remarque :</strong>
  <%= @ticket.remarque %>
</p>

<p>
  <strong>Garantie :</strong>
  <%= @ticket.garantie %>
</p>

</div>



<div class="price2">

<p>
  <strong>Total:</strong>
  <%= @ticket.total %> €
</p>

<p>
  <strong>Accompte:</strong>
  <%= @ticket.accompte  %> €
</p>

<p>
  <strong>Reduction:</strong>
  <%= @ticket.reduction %> €
</p>

<p>
  <strong>Total à payer:</strong>

   <% if @ticket.reduction == nil %>

   <% @ticket.reduction == 0 
      
   %>

   <% elsif @ticket.accompte == nil  %>

   <% @ticket.accompte == 0  %>

   <% end %>

   <%= @ticket.total + @ticket.accompte - @ticket.reduction %> €


</p>
 <hr>

<p style="font-size: 16px;">
  <strong>PREUVE DE DEPOT A CONSERVER</strong>
  MOBILE FRANCE 13 RUE DE BELFORT 71100 CHALON-SUR-SAÔNE
Tel : +33 9 83 03 72 94 Port. : +33 7 67 00 32 33 
contact@mobilecenter.fr N° SIRET : 89490645200012 Capital : 3 000 €
TVA non applicable - article 293 B du CGI 
Garantie (hors casse et oxydation)
</p>

 


 





 </div>
  






